export const typeRedux = {
  FETCH_MEMBER: 'FETCH_MEMBER',
  FETCH_MEMBERS: 'FETCH_MEMBERS',
  CREATE_MEMBER: 'CREATE_MEMBER',

  FETCH_REGIS: 'FETCH_REGIS',
  CREATE_REGIS: 'CREATE_REGIS',
  FETCH_REGIS_CATEGORY_NAME: " FETCH_REGIS_CATEGORY_NAME",

  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',

  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
};
